---

- name: Use pool.ntp.org for NTP
  ansible.builtin.lineinfile:
    path: /etc/systemd/timesyncd.conf
    regexp: '^#NTP='
    line: NTP={{ base_ntp }}
  notify:
    - Restart systemd-timesyncd

- name: Create tmp.mount
  ansible.builtin.copy:
    src: /usr/share/systemd/tmp.mount
    dest: /etc/systemd/system
    remote_src: true
    mode: '0644'

- name: Mount /tmp as tmpfs
  ansible.builtin.systemd:
    name: tmp.mount
    enabled: true
    state: started

- name: Create build directory
  ansible.builtin.file:
    path: /tmp/build
    state: directory
    mode: '0777'

- name: Create cpupower.service
  ansible.builtin.copy:
    src: cpupower.service
    dest: /etc/systemd/system
    mode: '0644'

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
